f=[1;1;];
intcon=[];
A=[1 1;];
b=[-22];
Aeq=[];
beq=[];
lb=[0;0;];
ub=[10;10;];
x0=[91 81;];
x0=[];
options=[];
%options = optimoptions('intlinprog','RootLPAlgorithm','primal-simplex');
%options = optimoptions('intlinprog','RootLPAlgorithm','dual-simplex');
%options = optimoptions('intlinprog','Display','iter','RootLPAlgorithm','dual-simplex','Heuristics','none');
[x,fval,eflag,out] = intlinprog(f,intcon,A,b,Aeq,beq,lb,ub,x0,options);
fprintf("x1=%d\nx2=%d\n",x(1,1),x(2,1));